import '@/styles/globals.css';
import Head from 'next/head';
import { Header, Footer } from '@/components';
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title> JORDAN SHOES | NEXT JS </title>
        <meta name='description' content='Generated By Rafay Dev.'></meta>
        <meta name='viewport' content='width=device-width, initial-scale=1'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header/>
      <Component {...pageProps} />
      <Footer/>
    </>
  );
}
