import '@/styles/globals.css';
import Head from 'next/head';
import { Header, Footer } from '@/components';
import { StateContext } from '@/context/StateContext';
import { Toaster } from 'react-hot-toast';

export default function App({ Component, pageProps }) {
  return (
    <>
      <StateContext>
          <Head>
            <title> ADIDAS SHOES | NEXT JS </title>
            <meta name='description' content='Generated By Rafay Dev.'></meta>
            <meta name='viewport' content='width=device-width, initial-scale=1'></meta>
            <link rel='icon' href='/favicon.ico' />
          </Head>
        <Header/>
        <Toaster/>
          <Component {...pageProps} />
        <Footer/>
      </StateContext>
    </>
  );
}
